import "./globals.css";
import { Noto_Sans } from "next/font/google";
import Nav from "@/components/nav";
import Header from "@/components/header";

const ourFont = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "200", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ourFont.className}>
        <Header />
        <hgroup className=" flex flex-row h-screen w-screen overflow-hidden pt-16">
          <Nav />
          {children}
        </hgroup>
      </body>
    </html>
  );
}
